-- Neue Zutaten für keepr DB
-- Ausführen mit: sqlite3 speisekammer.db < insert_ingredients.sql

INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rindfleisch', 'rindfleisch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schweinefleisch', 'schweinefleisch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Putenbrustfilet', 'putenbrustfilet', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Lammfleisch', 'lammfleisch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Entenbrust', 'entenbrust', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kalbfleisch', 'kalbfleisch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wildfleisch', 'wildfleisch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kaninchen', 'kaninchen', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bratwurst', 'bratwurst', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Würstchen', 'wuestchen', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Salami', 'salami', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Chorizo', 'chorizo', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schweinebauch', 'schweinebauch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rindersteak', 'rindersteak', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schweinekotelett', 'schweinekotelett', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mortadella', 'mortadella', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Leberwurst', 'leberwurst', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hühnerleber', 'huehnerleber', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rindergulasch', 'rindergulasch', 'Fleisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kabeljau', 'kabeljau', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Forelle', 'forelle', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hering', 'hering', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Makrele', 'makrele', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Räucherlachs', 'raeucherlachs', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sardinen', 'sardinen', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Miesmuscheln', 'miesmuscheln', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Calamari', 'calamari', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Scholle', 'scholle', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rotbarsch', 'rotbarsch', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Seelachs', 'seelachs', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Dorade', 'dorade', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wolfsbarsch', 'wolfsbarsch', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Jakobsmuscheln', 'jakobsmuscheln', 'Fisch');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Fenchel', 'fenchel', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rote Bete', 'rote-bete', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Spargel weiß', 'spargel-weiss', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Spargel grün', 'spargel-gruen', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kohlrabi', 'kohlrabi', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rosenkohl', 'rosenkohl', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mangold', 'mangold', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pak Choi', 'pak-choi', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rucola', 'rucola', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Feldsalat', 'feldsalat', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Eisbergsalat', 'eisbergsalat', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Radicchio', 'radicchio', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Endivie', 'endivie', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Frühlingszwiebeln', 'fruehlungszwiebeln', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schalotten', 'schalotten', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rhabarber', 'rhabarber', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Radieschen', 'radieschen', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pastinaken', 'pastinaken', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Zuckererbsen', 'zuckererbsen', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Shiitake-Pilze', 'shiitake', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pfifferlinge', 'pfifferlinge', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Steinpilze', 'steinpilze', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Austernpilze', 'austernpilze', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Artischocken', 'artischocken', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Jalapeños', 'jalapenos', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Getrocknete Tomaten', 'getrocknete-tomaten', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Oliven', 'oliven', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kapern', 'kapern', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bambussprossen', 'bambussprossen', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Blattspinat', 'blattspinat', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Topinambur', 'topinambur', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kresse', 'kresse', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bärlauch', 'baerlauch', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sauerkraut', 'sauerkraut', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Cornichons', 'cornichons', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Saure Gurken', 'saure-gurken', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kochbananen', 'kochbananen', 'Gemüse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Birnen', 'birnen', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kirschen', 'kirschen', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pflaumen', 'pflaumen', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kiwi', 'kiwi', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Grapefruit', 'grapefruit', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wassermelone', 'wassermelone', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Honigmelone', 'honigmelone', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Papaya', 'papaya', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Granatapfel', 'granatapfel', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Feigen', 'feigen', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Datteln', 'datteln', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Aprikosen', 'aprikosen', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pfirsiche', 'pfirsiche', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Limette', 'limette', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Cranberries', 'cranberries', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Johannisbeeren', 'johannisbeeren', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Maracuja', 'maracuja', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Physalis', 'physalis', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Stachelbeeren', 'stachelbeeren', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Brombeeren', 'brombeeren', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kokosnuss', 'kokosnuss', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kumquats', 'kumquats', 'Obst');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mascarpone', 'mascarpone', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ricotta', 'ricotta', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Camembert', 'camembert', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Brie', 'brie', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Emmentaler', 'emmentaler', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bergkäse', 'bergkaese', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Halloumi', 'halloumi', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ziegenkäse', 'ziegenkaese', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Gruyère', 'gruyere', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Buttermilch', 'buttermilch', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kefir', 'kefir', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schlagsahne', 'schlagsahne', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Saure Sahne', 'saure-sahne', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hüttenkäse', 'huettenkaese', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kondensmilch', 'kondensmilch', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Fusilli', 'fusilli', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tagliatelle', 'tagliatelle', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rigatoni', 'rigatoni', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Lasagneblätter', 'lasagneblaetter', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Gnocchi', 'gnocchi', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Spätzle', 'spaetzle', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Couscous', 'couscous', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bulgur', 'bulgur', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Polenta', 'polenta', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hirse', 'hirse', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Dinkelmehl', 'dinkelmehl', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Vollkornmehl', 'vollkornmehl', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Speisestärke', 'speisestaerke', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Paniermehl', 'paniermehl', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Glasnudeln', 'glasnudeln', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Reisnudeln', 'reisnudeln', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Basmati-Reis', 'basmati-reis', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wildreis', 'wildreis', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Amaranth', 'amaranth', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tortellini', 'tortellini', 'Getreide');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kidneybohnen', 'kidneybohnen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schwarze Bohnen', 'schwarze-bohnen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Weißbohnen', 'weissbohnen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rote Linsen', 'rote-linsen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Edamame', 'edamame', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tofu', 'tofu', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tempeh', 'tempeh', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sojasprossen', 'sojasprossen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mungobohnen', 'mungobohnen', 'Hülsenfrüchte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Vollkornbrot', 'vollkornbrot', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ciabatta', 'ciabatta', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Baguette', 'baguette', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Brötchen', 'broetchen', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Laugengebäck', 'laugengebaeck', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pita-Brot', 'pita-brot', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wrap', 'wrap', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Knäckebrot', 'knaeckebrot', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Croissant', 'croissant', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pumpernickel', 'pumpernickel', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Naan', 'naan', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Blätterteig', 'blaetterteig', 'Backwaren');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kreuzkümmel', 'kreuzku emmel', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Koriandersamen', 'koriandersamen', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Thymian', 'thymian', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Majoran', 'majoran', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Salbei', 'salbei', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Lorbeer', 'lorbeer', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Muskatnuss', 'muskatnuss', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kurkuma', 'kurkuma', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Dill', 'dill', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schnittlauch', 'schnittlauch', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Minze', 'minze', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Koriander frisch', 'koriander-frisch', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Chiliflocken', 'chiliflocken', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sesam', 'sesam', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mohn', 'mohn', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Vanille', 'vanille', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kardamom', 'kardamom', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sternanis', 'sternanis', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kümmel', 'kuemmel', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Estragon', 'estragon', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Zitronengras', 'zitronengras', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Schwarzkümmel', 'schwarzkuemmel', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sumach', 'sumach', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Garam Masala', 'garam-masala', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wacholderbeeren', 'wacholderbeeren', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Piment', 'piment', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Liebstöckel', 'liebstoeckel', 'Gewürze');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kokosöl', 'kokosoel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rapsöl', 'rapsoel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sonnenblumenöl', 'sonnenblumenoel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sesamöl', 'sesamoel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ghee', 'ghee', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Avocadoöl', 'avocadooel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kürbiskernöl', 'kuerbiskernoel', 'Öle & Fette');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Cashewkerne', 'cashewkerne', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Haselnüsse', 'haselnuesse', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pinienkerne', 'pinienkerne', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sonnenblumenkerne', 'sonnenblumenkerne', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kürbiskerne', 'kuerbiskerne', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Leinsamen', 'leinsamen', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Chiasamen', 'chiasamen', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pistazien', 'pistazien', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kokosflocken', 'kokosflocken', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Erdnüsse', 'erdnuesse', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pekannüsse', 'pekannuesse', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Macadamia', 'macadamia', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Maronen', 'maronen', 'Nüsse');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ketchup', 'ketchup', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mayonnaise', 'mayonnaise', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Balsamico', 'balsamico', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Apfelessig', 'apfelessig', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sriracha', 'sriracha', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tabasco', 'tabasco', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Pesto', 'pesto', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tahini', 'tahini', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hoisin-Sauce', 'hoisin', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Fischsauce', 'fischsauce', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Teriyaki-Sauce', 'teriyaki', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Worcestershire', 'worcestershire', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tomatensoße', 'tomatensauce', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Gemüsebrühe', 'gemuesebruehe', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hühnerbrühe', 'huehnerbrue', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Miso-Paste', 'miso', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sambal Oelek', 'sambal-oelek', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rote Currypaste', 'rote-currypaste', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ajvar', 'ajvar', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Hummus', 'hummus', 'Saucen');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Backpulver', 'backpulver', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Trockenhefe', 'trockenhefe', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Frischhefe', 'frischhefe', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Puderzucker', 'puderzucker', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Brauner Zucker', 'brauner-zucker', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Ahornsirup', 'ahornsirup', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Agavensirup', 'agavensirup', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kakaopulver', 'kakaopulver', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Zartbitterschokolade', 'zartbitter', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Natron', 'natron', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Gelatine', 'gelatine', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mandelmehl', 'mandelmehl', 'Backzutaten');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Mais (Dose)', 'mais-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bohnen (Dose)', 'bohnen-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kichererbsen (Dose)', 'kichererbsen-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Thunfisch (Dose)', 'thunfisch-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Artischockenherzen', 'artischockenherzen', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rote Bete (Glas)', 'rote-bete-glas', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sauerkraut (Dose)', 'sauerkraut-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Linsen (Dose)', 'linsen-dose', 'Konserven');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Weißwein', 'weisswein', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Rotwein', 'rotwein', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Bier', 'bier', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Kokoswasser', 'kokoswasser', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Orangensaft', 'orangensaft', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Zitronensaft', 'zitronensaft', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Meerrettich', 'meerrettich', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Wasabi', 'wasabi', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Sauerrahm', 'sauerrahm', 'Milchprodukte');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Tamarinde', 'tamarinde', 'Sonstiges');
INSERT OR IGNORE INTO ingredients (name, slug, category) VALUES ('Jackfrucht', 'jackfrucht', 'Obst');
